name: Update Podcast Feed

on:
    schedule:
        - cron: "*/20 5-11,16-21 * * *" # Run every 20 minutes between 5am - 11pm and 4pm - 9pm UTC
    workflow_dispatch:
        inputs:
            rss_source_url:
                description: "URL to the RSS feed"
                default: "https://www.tagesschau.de/multimedia/sendung/tagesschau_in_100_sekunden/podcast-ts100-audio-100~podcast.xml"
                required: true
                type: string

jobs:
    update:
        runs-on: ubuntu-latest
        env:
            RSS_SOURCE_URL: ${{ inputs.rss_source_url || 'https://www.tagesschau.de/multimedia/sendung/tagesschau_in_100_sekunden/podcast-ts100-audio-100~podcast.xml' }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Download source feed
              run: curl -s "${{ env.RSS_SOURCE_URL }}" -o data/source.xml

            - name: Run feed generator
              run: python src/feed_generator.py

            - name: Commit and push changes
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add data/episodes.json docs/feed.xml
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Update podcast feed" && git push)
